### ISSUE TITLE
Missing content availabe on Channel 13's VOD but not in the add-on

### ISSUE THREAD

**Issue by StentMan** [Fishenzon/fishenzon.github.io#6]
Here's the link to the show:
https://13tv.co.il/item/documentary/movies/yz5nm-903297575/?pid=571123&cid=903021891

It seems like it's a one-time documentary, not part of any TV show. Maybe add a category "סרטים" that will contain all of these? I don't know, just a thought.

**Comment by Fishenzon** [comment]
צהרים טובים.
זה נמצא תחת דוקו-רשת
